[server]
address = "game.openrsc.com:43235"

[ocr]
ocr_type = "hash"

[data]
directory    = "data"
landscape    = "Authentic_P2PLandscape.orsc"
item_defs    = "ItemDefs.json"
scenery_locs = "SceneryLocs.json"
tile_defs    = "TileDefs.json"
door_defs    = "DoorDefs.json"
object_defs  = "ObjectDefs.json"
word_hashes  = "Words.json"
rsa_key_file = "RSA.json"

[accounts]
directory = "accounts"

[client]
client_version = 10010

[script]
directory = "scripts"

[logs]
directory                  = "logs"
progress_reports           = "progress_reports"
overwrite_progress_reports = true
