# Use OpenJDK 8 provided by Eclipse Temurin since the main jdk images have been
# deprecated for a while now. Let's also use Ubuntu Jammy (22.04), which is the
# most recent LTS release.
# Upstream reference: https://github.com/adoptium/containers
default:
  image: eclipse-temurin:8-jdk-jammy

stages:
  - format
  - build
  - pages

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apt-get update --quiet --assume-yes
  - apt-get install --quiet --assume-yes git make

# git rev-list --count does not work correctly with the default settings.
variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

# Invalidate cache if the gradle-wrapper.properties file changes.
# All wrapper binaries, dependency caches & release changelog notifications
# (that bit of text that appears when the wrapper is updated) are cached
# for use in later invocations of the CI.
cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - .gradle/notifications

# Check if source code is formatted properly.
format:
  stage: format
  script:
    - make check-format

# Explicitly state to gradle wrapper that we want the cache to be enabled,
# build a release zip, then upload the zip artifact to Gitlab CI for end-users
# to download.
build:
  stage: build
  script: 
    - make release
    - mv *.zip IdleRSC.zip
  artifacts:
    name: IdleRSC
    paths:
      - IdleRSC.zip

# Upload Javadoc API documentation to Gitlab pages.
pages:
  stage: pages
  script: 
    - make build-javadoc
  artifacts:
    paths:
      - public

# TODO - upload readme and doc to wiki https://gitlab.com/open-runescape-classic/idlersc/-/wikis/pages